### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Dongmo12**

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @Dongmo12, 
You have done a very job, everything working fine except you're not using the right HTML tags.
checkout this [link](https://www.themelocation.com/best-html5-practices) to see best HTML tags practice.
Here is the checklist for your project from Microverse project guidelines.
- To consider the project 'complete' it must satisfy the following points:
## General
- [x] The project has a descriptive README.md
(it should include author, good practice to have live version and programming language used)
## Navigation Bar
- [ ] It is wrapped around a pair of `<nav>` HTML tags.
- [x] It has the Newsweek logo on the leftmost part of the navbar
## Top Stories
* [ ] It is wrapped by a pair of opening and closing `<section>` HTML tags
* [ ] It contains a story wrapped by a pair of opening and closing `<article>` HTML tags
* [x] It is aligned to the middle of the main content
## More Stories
- [ ] It is wrapped by a pair of opening and closing `<section>` HTML tags.
## Featured Stories
* [ ] It is wrapped by a pair of opening and closing `<section>` HTML tags.
* [ ] It has seven articles wrapped by a pair of opening and closing `<article>` HTML tags
* [x] It is aligned to the left of the main content
## Opinion
* [ ] It is wrapped by a pair of opening and closing `<section>` HTML tags
* [x] It has a header with the text: `Opinion`
- [ ] It has eight articles wrapped by a pair of opening and closing `<article>` HTML tags
## In the Magazine, Editor's picks, Featured Slideshow
* [ ] It is wrapped by a pair of opening and closing `<section>` HTML tags
## Footer
* [ ] It is wrapped by a pair of opening and closing `<footer>` HTML tags

Make these tags changes while :+1:  await you 
Kindly submit another code review form.

**Comment by bellom** [comment]
Hi, i can see you have a lot of questions, kindly know that all reviewers follows Microverse review guidelines.
And for the questions about tags, i sent you a link that could help you out, truly you added some of the tags but you didn't use them correctly, if you could checkout the Iink, you will see the best practice on how to use HTML tags.
And don't get confused, you already passed those that are checked, you are to work on those that are not being checked.
I hope that clarify your doubt ?
Anymore questions ?

**Kindly go through the checklist and make these changes to the unchecked list**
example; _your navigation bar should be wrapped with `<nav> tag`._
Kindly submit for re-review

**Comment by Ispirett** [comment]
Hey!  wonderful job with some of the changes you have made so far and great job using bootstrap :100:  There are still some issues that need addressing.
- [x] Some of your images are not showing up  in you **OPINION** section, **EDITOR'S PICK** section, **FEATURED SLIDESHOWS** section and class Newsweek right before the footer

- [x] In the Magazine, Editor's picks, Featured Slideshow
  It is wrapped by a pair of opening and closing <section> HTML tags link `347`

please addresses these issues and submit for another code review

**Comment by samgaco** [comment]
Hi :hand: 

Well done working on the previous solicited changes :clap:  there is one more thing;

* **You should solve the issue with the vertical scrolling bar (it is not showing);** I see you are having issues with the scrollbars created by **overflow-auto**, you tried to solve it with;
```
::-webkit-scrollbar{
    display:none;
}
```

But the problem is that there are no scroll bars anywhere now, maybe you could try to solve your problem in a more elegant way trying to check solutions in _stack-overflow_, [here](https://stackoverflow.com/questions/20447384/cant-hide-scrollbar-when-using-overflow-auto) and [here](https://stackoverflow.com/questions/16670931/hide-scroll-bar-but-while-still-being-able-to-scroll/16671476) there are some questions related to your problem.

Please :pray:  Address this issue and submit again for another code review. Regards!

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Congratulations @Dongmo12 👏
Nicely done on this project
You can submit to master now.
Good luck with the next one

**Pull request merged**
